feat: configure ban list by yaml
ije/esm.sh pull request #466
Opened 2022-12-16 12:18 UTC by hjaurum

Supports config ban list by `.config.yml` instead of hard code.
For Issue #465 

Unit Test:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/11769853/208096473-5169404c-2a20-4eca-a927-80ac84ab710c.png">

Local Test:
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/11769853/208096385-bc434882-71a5-4dd2-b5e9-6caec3f04b16.png">

2022-12-16 12:56 UTC, ije requested changes

2022-12-16 12:56 UTC, ije commented on go.mod
> +	gopkg.in/yaml.v3 v3.0.1 // indirect
can we just use plain txt or JSON as the list file? i want to keep the deps as clear as possible.

2022-12-16 12:56 UTC, ije commented on server/config/config_test.go
> +func TestBanList_IsPackageBaned(t *testing.T) {
nice to see unit testing👍

2022-12-16 12:58 UTC, ije commented
@hjaurum great job! i suggest use plain txt or json as the list input to reduce go deps. thanks 🙏

2022-12-17 11:15 UTC, hjaurum commented on go.mod
> +	gopkg.in/yaml.v3 v3.0.1 // indirect
Sure, I have replace the YAML with JSON to reduce the deps.

2022-12-17 15:52 UTC, ije commented on server/config/config.go
> +type Configs struct {
i like the `Config` structure, maybe we should move all the options to here instead of using flag

2022-12-17 15:52 UTC, ije approved these changes

2022-12-17 15:54 UTC, ije commented
LGTM, nice job done 👍

2022-12-17 15:54 UTC, merged